import PostalMime from 'postal-mime'
// TYPE-ONLY, so it is erased at build time: the worker gains a compile-time
// contract with the endpoint and carries no application code. The two used to
// agree by memory — see the header of the file it points at.
import type { InboundEmailPayload } from '../../src/lib/inbound-email-payload'

// ---------------------------------------------------------------------------
// THE MAIL RECEIVER (Phase 6 §4 step 4).
//
// A SECOND WORKER, AND IT HAS TO BE. Cloudflare Email Routing delivers only to
// a Worker with an `email()` handler; the application is generated by OpenNext
// and exports a `fetch` handler it owns. Bolting a mail handler onto generated
// output would be a patch that survives exactly until the next OpenNext
// upgrade.
//
// It is also the right shape independently: a mail handler that throws must
// not be able to take the application down with it, and this one holds no
// database binding, no Prisma client and no secrets beyond the one bearer
// token it forwards with.
//
// THIS WORKER DECIDES NOTHING. It parses MIME and posts JSON. Which tenant the
// mail belongs to, whether it is a duplicate, what the reader makes of it and
// what the office is told are all decided in the application, where row-level
// security, permissions and the audit trail already live. A mail worker that
// knew about tenants would be a second place tenancy is decided.
//
// WHY A DEPENDENCY HERE AND NOT FOR THE ZIP (flag 37). The .xlsx case is a
// ZIP: a documented byte layout, a couple of hundred lines, and a wrong answer
// fails loudly. MIME is not that. Nested multipart, RFC 2047 encoded headers,
// quoted-printable, base64, per-part charsets — and a subtly wrong parse does
// not throw, it silently mangles a booking. `postal-mime` is purpose-built for
// this runtime and has NO dependencies of its own, which is the whole reason
// the no-SDK rule exists.
// ---------------------------------------------------------------------------

interface Env {
  /** Where the application lives. Not derived — the app may move. */
  ZEBRA_ORIGIN: string
  /** The shared secret the endpoint checks. */
  INBOUND_EMAIL_SECRET: string
}

/** Attachments worth spending a model call on. */
const READABLE = /^(application\/pdf|image\/(png|jpeg|webp|gif))$/

/**
 * Anything bigger than this is not a rate confirmation.
 *
 * The endpoint's own extraction cap is 10MB of base64; refusing here saves
 * sending it, and the message still lands with its body so a dispatcher sees
 * that something arrived.
 */
const MAX_ATTACHMENT_BYTES = 7 * 1024 * 1024

/**
 * The biggest message worth carrying whole.
 *
 * A Worker's request body is capped and base64 costs a third on top, so a
 * message past this is recorded WITHOUT its original rather than not recorded
 * at all — `rawBytes` still says how big it was, so the gap is visible instead
 * of looking like a message that never had attachments.
 */
const MAX_RAW_BYTES = 15 * 1024 * 1024

const handler = {
  async email(message: ForwardableEmailMessage, env: Env): Promise<void> {
    // THE WHOLE MESSAGE, READ ONCE. `message.raw` is a stream and a stream is
    // consumed by whoever gets there first — parsing it and then trying to
    // keep it would hand the endpoint an empty body. So the bytes are taken
    // first and the parser is given those.
    const raw = new Uint8Array(await new Response(message.raw).arrayBuffer())
    const parsed = await PostalMime.parse(raw)

    // The Message-ID is the mail system's own idempotency key and the endpoint
    // treats it as unique. A message without one is rare and still real, so it
    // gets a stable substitute rather than being dropped: same sender, same
    // subject and same minute is the same delivery retried.
    const messageId =
      parsed.messageId ??
      `<generated-${message.from}-${parsed.subject ?? ''}-${Math.floor(
        Date.now() / 60_000,
      )}@zebra.local>`

    const attachments = (parsed.attachments ?? [])
      .filter(
        (attachment) =>
          READABLE.test(attachment.mimeType ?? '') &&
          attachment.content instanceof ArrayBuffer &&
          attachment.content.byteLength > 0 &&
          attachment.content.byteLength <= MAX_ATTACHMENT_BYTES,
      )
      // ONE. The endpoint reads a single document, and sending four means
      // paying for four model calls to fill one form. A rate confirmation
      // email has one rate confirmation on it; the rest is a logo and a
      // signature block.
      .slice(0, 1)
      .map((attachment) => ({
        filename: attachment.filename ?? 'attachment',
        mimeType: attachment.mimeType ?? 'application/octet-stream',
        base64: base64Of(new Uint8Array(attachment.content as ArrayBuffer)),
      }))

    const body: InboundEmailPayload = {
      messageId,
      // `message.from` is the envelope sender, which is what actually
      // delivered this; `parsed.from` is the header, which anybody can write.
      // The envelope is the honest one.
      from: message.from,
      to: message.to,
      subject: parsed.subject ?? null,
      // Plain text if the sender bothered, otherwise the HTML flattened. A
      // booking email is usually both, and the plain part is the one without
      // three tables of layout in it.
      text: parsed.text ?? textFromHtml(parsed.html ?? ''),
      attachments,
      // SPEC §12: the dispatcher opens the original. The `.eml` is the
      // original — headers, body and every attachment inside it — and it is
      // the one artefact that cannot be reconstructed from anything else we
      // keep. Sent even when it is large, because a booking whose provenance
      // is missing is the thing a dispute turns on.
      raw: raw.byteLength <= MAX_RAW_BYTES ? base64Of(raw) : null,
      rawBytes: raw.byteLength,
    }

    const response = await fetch(`${env.ZEBRA_ORIGIN}/api/inbound-email`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        authorization: `Bearer ${env.INBOUND_EMAIL_SECRET}`,
      },
      body: JSON.stringify(body),
    })

    if (!response.ok) {
      // THROWING IS THE POINT. Cloudflare retries a message whose handler
      // failed, and a booking that vanished because the application was
      // restarting is the one failure mode this whole path exists to prevent.
      // The message is not rejected — `message.setReject()` bounces it back to
      // the sender, which would tell Amazon we are broken.
      const detail = await response.text().catch(() => '')
      throw new Error(
        `zebra rejected ${messageId}: ${response.status} ${detail.slice(0, 200)}`,
      )
    }
  },
}

export default handler

/** Bytes to base64, chunked — `fromCharCode(...bytes)` blows up on a megabyte. */
function base64Of(bytes: Uint8Array): string {
  let binary = ''
  const CHUNK = 0x8000
  for (let index = 0; index < bytes.length; index += CHUNK) {
    binary += String.fromCharCode(...bytes.subarray(index, index + CHUNK))
  }
  return btoa(binary)
}

/**
 * HTML to something a reader can work with.
 *
 * DELIBERATELY CRUDE. This is not a renderer — the extraction contract reads
 * words, and what it needs is the words in the order they were written with
 * the tags gone. Scripts and styles are dropped whole because their contents
 * are not words; block-level tags become newlines because a booking email's
 * meaning lives in its line breaks.
 */
function textFromHtml(html: string): string {
  return html
    .replace(/<(script|style)[\s\S]*?<\/\1>/gi, ' ')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/(p|div|tr|li|h[1-6]|table)>/gi, '\n')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}
